//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NarinGumruk_Example
{
    using System;
    using System.Collections.Generic;
    
    public partial class KullaniciExample_TBL
    {
        public int KullaniciID { get; set; }
        public string KullaniciAdi { get; set; }
        public Nullable<short> Yas { get; set; }
        public string DogumYeri { get; set; }
    }
}
