//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NarinGumruk_Example
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Narin_Gumruk_ExampleProjectEntities : DbContext
    {
        public Narin_Gumruk_ExampleProjectEntities()
            : base("name=Narin_Gumruk_ExampleProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<KullaniciExample_TBL> KullaniciExample_TBL { get; set; }
        public virtual DbSet<Sehir_TBL> Sehir_TBL { get; set; }
    }
}
